import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  SessionWrapper  from "../components/Providers/SessionProvider"
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MtaxOnline Accounting: Payroll Outsourcing",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionWrapper>
          {children}
        </SessionWrapper>
        </body>
    </html>
  );
}
